spring:
  datasource:
    url: jdbc:mysql://localhost:3306/roomsync
    username: root
    password: sameer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
